Feature/use stream
dataiku/dss-plugin-excel-sheet-importer pull request #4
Opened 2023-07-18 14:10 UTC by alexbourret

2023-08-16 11:57 UTC, liamlynch-data commented
This is the ticket
https://app.shortcut.com/dataiku/story/66234/use-dataiku-folder-api-for-read-instead-of-direct-access-as-it-doesn-t-work-with-non-local-fs

2023-08-17 12:40 UTC, liamlynch-data requested changes
I have tested with local and S3 managed folders and it works. 
However there a a couple of things to fix and/or improve on.

2023-08-17 12:40 UTC, liamlynch-data commented on python-runnables/macro-excel-importer/runnable.py
> +                    ss = openpyxl.load_workbook(BytesIO(file_handle.read()))
I think we should probably move this out of the for loop - it's loading the same data from the  file again and again. When things are remote via S3 etc this might have an impact.

2023-08-17 12:40 UTC, liamlynch-data commented on python-runnables/macro-excel-importer/runnable.py
> +                sheets_names = pd.ExcelFile(file_handle).sheet_names
Perhaps there is a way of getting a sheet name list without making a separate call to download the data - or a way to iterate the sheets once we have downloaded it all.  A related question was why we need to use both pandas ExcelFile and openpyxl. In fact I think the ss object from openpyxl below might be able to give us the sheets like this:

ss.sheetnames

As this won't change the way the data is read it is probably a safe thing to do?

2023-08-17 12:40 UTC, liamlynch-data commented on python-runnables/macro-excel-importer/runnable.py
> +                    ss = openpyxl.load_workbook(BytesIO(file_handle.read()))
So coupled with the previous comment, we could do this outside the loop, keep using the same ss object and iterate through `ss.sheetnames`

2023-08-17 12:40 UTC, liamlynch-data commented on python-runnables/macro-excel-importer/runnable.py
> +                    title = '_'.join((file_name.split(".")[0] + "_" + sheet).split())
I think maybe we could  remove the join and split operations that replace whitespace with `_` here as we do them on the next line anyway

Would make it more readable as the file name stuff is now mixed in with it, that makes it less self explanatory.

2023-08-17 12:40 UTC, liamlynch-data commented on python-runnables/macro-excel-importer/runnable.py
> +                        dataset.set_schema({'columns': [{'name': column, 'type': 'string'} for column, column_type in df.dtypes.items()]})
We're downloading the file again here. Perhaps we could get rid of this separate operation but I think it might be a bit more tricky in this case and it is ok to leave it for now.

2023-08-17 12:40 UTC, liamlynch-data commented on plugin.json
> +    "version": "1.0.2",
It looks like we have to update this in the makefile also - currently it is building 1.0.1

2023-08-17 14:57 UTC, liamlynch-data commented on python-runnables/macro-excel-importer/runnable.py
> +                    ss = openpyxl.load_workbook(BytesIO(file_handle.read()))
Addressed here: https://github.com/dataiku/dss-plugin-excel-sheet-importer/pull/4/commits/c532440018139367f78aef5ccc70cfe1560a0f39

2023-08-17 14:57 UTC, liamlynch-data commented on python-runnables/macro-excel-importer/runnable.py
> +                sheets_names = pd.ExcelFile(file_handle).sheet_names
Addressed here: https://github.com/dataiku/dss-plugin-excel-sheet-importer/pull/4/commits/c532440018139367f78aef5ccc70cfe1560a0f39

2023-08-17 14:57 UTC, liamlynch-data commented on python-runnables/macro-excel-importer/runnable.py
> +                    title = '_'.join((file_name.split(".")[0] + "_" + sheet).split())
Addressed here: https://github.com/dataiku/dss-plugin-excel-sheet-importer/pull/4/commits/c532440018139367f78aef5ccc70cfe1560a0f39

And tested with sheet names with and without the file name in them

2023-08-17 14:58 UTC, liamlynch-data commented on python-runnables/macro-excel-importer/runnable.py
> +                        dataset.set_schema({'columns': [{'name': column, 'type': 'string'} for column, column_type in df.dtypes.items()]})
I made an attempt at this but I had an issue with handle the BytesIo object and the stream already being closed, so I left things as they are

2023-08-17 15:01 UTC, liamlynch-data commented on plugin.json
> +    "version": "1.0.2",
In the last commit (which brought in the merge of the plugin python update) I set everything to 1.1.1 
https://github.com/dataiku/dss-plugin-excel-sheet-importer/pull/4/commits/9c0de143d6224664640e5d7b42e24519e08eeecc

2023-08-17 15:02 UTC, liamlynch-data approved these changes

2023-08-17 16:21 UTC, liamlynch-data commented
@alexbourret  - I made a review then addressed the changes myself - then retested with S3 covering the cases of spaces and various punctuation in the name of sheets, file name in or not in the sheet name, etc.
Also I updated from master as the python supported version update had happened.

And  made it skip non-excel files (based on xlsx extension) as it was not handling these so they broke things

Version is now 1.2.0

Please take a look when you are back and merge if happy.

2023-08-18 05:32 UTC, alexbourret commented
Thank you for your review and modifications @liamlynch-data  ! I just changed two things:
- As long as we have to maintain two branches, I thing we stuck with 1.0.x for DSS-11 and 1.1.x for 12. So I've set the version back to 1.1.1 for this target master branch. I'll do another PR for v1.0.2 targeting a release/11 branch later.
- I've replace the skipping xlsx based on file extension part with a try / except on the xlsx decoding.

Let me know if you're happy with the change and I'll merge / and create a release/11 PR in the process...

2023-08-18 08:13 UTC, liamlynch-data commented
@alexbourret yes that is a better way to handle non-excel files.
I did a quick retest and it's all good - happy for you to go ahead

2023-08-18 08:27 UTC, merged